### ISSUE TITLE
颜色的部分可以 进行 手动输入吗 

### ISSUE THREAD

**Issue by lhj5426** [hbl917070/InstantSubtitle#1]
![image](https://github.com/hbl917070/InstantSubtitle/assets/30548000/5d194402-7cf5-4055-88ba-075cc94d9476)
首先 真的非常感谢大佬更新 这个多年前的小工具
新增的功能让字体看着更舒服也更现代

就是这个 调解 有点不太方便 
要是能手动输入的话
![image](https://github.com/hbl917070/InstantSubtitle/assets/30548000/6465a47e-2cf0-4805-bdab-8164c59c747f)
可以像这样 通过其他的取色器 快速设置字体颜色

**Comment by hbl917070** [comment]
這個專案當初是用 WPF 開發的，那時找到可以選擇顏色的套件就只有這個
如果要用其他更好的顏色選擇器，就只能用 webview2 整個重寫
用 webview2 除了可以用更好的顏色選擇器，而且可以用 edge 內建的那些最新的語音模型
但缺點是，運行成本會增加，而且重寫需要不少時間

所以目前沒有計劃重構這個專案

**Comment by lhj5426** [comment]
> 這個專案當初是用 WPF 開發的，那時找到可以選擇顏色的套件就只有這個 如果要用其他更好的顏色選擇器，就只能用 webview2 整個重寫 用 webview2 除了可以用更好的顏色選擇器，而且可以用 edge 內建的那些最新的語音模型 但缺點是，運行成本會增加，而且重寫需要不少時間
> 
> 所以目前沒有計劃重構這個專案

嗯 感谢 您回复  我明白了嘻嘻 再次感谢您的更新
